/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Student = IDL.Record({
  'resultStatus' : IDL.Text,
  'name' : IDL.Text,
  'registrationNumber' : IDL.Text,
  'fatherName' : IDL.Text,
  'address' : IDL.Text,
  'batch' : IDL.Text,
  'phone' : IDL.Text,
  'course' : IDL.Text,
  'remarks' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Alumni = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'organization' : IDL.Text,
  'course' : IDL.Text,
});
export const Course = IDL.Record({
  'id' : IDL.Nat,
  'duration' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'eligibility' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const NoticeCategory = IDL.Variant({
  'examination' : IDL.Null,
  'admission' : IDL.Null,
  'general' : IDL.Null,
});
export const Notice = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : IDL.Int,
  'isActive' : IDL.Bool,
  'category' : NoticeCategory,
});
export const Result = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'pdfLink' : IDL.Text,
  'date' : IDL.Int,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'examType' : IDL.Text,
});
export const GalleryItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'blob' : ExternalBlob,
  'isActive' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const ContactInfo = IDL.Record({
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addStudent' : IDL.Func([Student], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAlumni' : IDL.Func([Alumni], [IDL.Nat], []),
  'createCourse' : IDL.Func([Course], [IDL.Nat], []),
  'createGalleryItem' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Nat], []),
  'createNotice' : IDL.Func([Notice], [IDL.Nat], []),
  'createResult' : IDL.Func([Result], [IDL.Nat], []),
  'deleteAlumni' : IDL.Func([IDL.Nat], [], []),
  'deleteCourse' : IDL.Func([IDL.Nat], [], []),
  'deleteGalleryItem' : IDL.Func([IDL.Nat], [], []),
  'deleteNotice' : IDL.Func([IDL.Nat], [], []),
  'deleteResult' : IDL.Func([IDL.Nat], [], []),
  'deleteStudent' : IDL.Func([IDL.Text], [], []),
  'getAboutText' : IDL.Func([], [IDL.Text], ['query']),
  'getAllAlumni' : IDL.Func([], [IDL.Vec(Alumni)], ['query']),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getAllNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
  'getAllResults' : IDL.Func([], [IDL.Vec(Result)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAlumni' : IDL.Func([IDL.Nat], [IDL.Opt(Alumni)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  'getCourse' : IDL.Func([IDL.Nat], [IDL.Opt(Course)], ['query']),
  'getGalleryItem' : IDL.Func([IDL.Nat], [IDL.Opt(GalleryItem)], ['query']),
  'getNotice' : IDL.Func([IDL.Nat], [IDL.Opt(Notice)], ['query']),
  'getResult' : IDL.Func([IDL.Nat], [IDL.Opt(Result)], ['query']),
  'getStudent' : IDL.Func([IDL.Text], [IDL.Opt(Student)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAboutText' : IDL.Func([IDL.Text], [], []),
  'updateAlumni' : IDL.Func([IDL.Nat, Alumni], [], []),
  'updateContactInfo' : IDL.Func([ContactInfo], [], []),
  'updateCourse' : IDL.Func([IDL.Nat, Course], [], []),
  'updateGalleryItem' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateNotice' : IDL.Func([IDL.Nat, Notice], [], []),
  'updateResult' : IDL.Func([IDL.Nat, Result], [], []),
  'updateStudent' : IDL.Func([Student], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Student = IDL.Record({
    'resultStatus' : IDL.Text,
    'name' : IDL.Text,
    'registrationNumber' : IDL.Text,
    'fatherName' : IDL.Text,
    'address' : IDL.Text,
    'batch' : IDL.Text,
    'phone' : IDL.Text,
    'course' : IDL.Text,
    'remarks' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Alumni = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'organization' : IDL.Text,
    'course' : IDL.Text,
  });
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'duration' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'eligibility' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const NoticeCategory = IDL.Variant({
    'examination' : IDL.Null,
    'admission' : IDL.Null,
    'general' : IDL.Null,
  });
  const Notice = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : IDL.Int,
    'isActive' : IDL.Bool,
    'category' : NoticeCategory,
  });
  const Result = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'pdfLink' : IDL.Text,
    'date' : IDL.Int,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'examType' : IDL.Text,
  });
  const GalleryItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'blob' : ExternalBlob,
    'isActive' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const ContactInfo = IDL.Record({
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addStudent' : IDL.Func([Student], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAlumni' : IDL.Func([Alumni], [IDL.Nat], []),
    'createCourse' : IDL.Func([Course], [IDL.Nat], []),
    'createGalleryItem' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Nat], []),
    'createNotice' : IDL.Func([Notice], [IDL.Nat], []),
    'createResult' : IDL.Func([Result], [IDL.Nat], []),
    'deleteAlumni' : IDL.Func([IDL.Nat], [], []),
    'deleteCourse' : IDL.Func([IDL.Nat], [], []),
    'deleteGalleryItem' : IDL.Func([IDL.Nat], [], []),
    'deleteNotice' : IDL.Func([IDL.Nat], [], []),
    'deleteResult' : IDL.Func([IDL.Nat], [], []),
    'deleteStudent' : IDL.Func([IDL.Text], [], []),
    'getAboutText' : IDL.Func([], [IDL.Text], ['query']),
    'getAllAlumni' : IDL.Func([], [IDL.Vec(Alumni)], ['query']),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getAllNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
    'getAllResults' : IDL.Func([], [IDL.Vec(Result)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAlumni' : IDL.Func([IDL.Nat], [IDL.Opt(Alumni)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
    'getCourse' : IDL.Func([IDL.Nat], [IDL.Opt(Course)], ['query']),
    'getGalleryItem' : IDL.Func([IDL.Nat], [IDL.Opt(GalleryItem)], ['query']),
    'getNotice' : IDL.Func([IDL.Nat], [IDL.Opt(Notice)], ['query']),
    'getResult' : IDL.Func([IDL.Nat], [IDL.Opt(Result)], ['query']),
    'getStudent' : IDL.Func([IDL.Text], [IDL.Opt(Student)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAboutText' : IDL.Func([IDL.Text], [], []),
    'updateAlumni' : IDL.Func([IDL.Nat, Alumni], [], []),
    'updateContactInfo' : IDL.Func([ContactInfo], [], []),
    'updateCourse' : IDL.Func([IDL.Nat, Course], [], []),
    'updateGalleryItem' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateNotice' : IDL.Func([IDL.Nat, Notice], [], []),
    'updateResult' : IDL.Func([IDL.Nat, Result], [], []),
    'updateStudent' : IDL.Func([Student], [], []),
  });
};

export const init = ({ IDL }) => { return []; };