/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alumni {
  'id' : bigint,
  'name' : string,
  'isActive' : boolean,
  'organization' : string,
  'course' : string,
}
export interface ContactInfo {
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface Course {
  'id' : bigint,
  'duration' : string,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'eligibility' : string,
}
export type ExternalBlob = Uint8Array;
export interface GalleryItem {
  'id' : bigint,
  'title' : string,
  'blob' : ExternalBlob,
  'isActive' : boolean,
}
export interface Notice {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'date' : bigint,
  'isActive' : boolean,
  'category' : NoticeCategory,
}
export type NoticeCategory = { 'examination' : null } |
  { 'admission' : null } |
  { 'general' : null };
export interface Result {
  'id' : bigint,
  'title' : string,
  'pdfLink' : string,
  'date' : bigint,
  'description' : string,
  'isActive' : boolean,
  'examType' : string,
}
export interface Student {
  'resultStatus' : string,
  'name' : string,
  'registrationNumber' : string,
  'fatherName' : string,
  'address' : string,
  'batch' : string,
  'phone' : string,
  'course' : string,
  'remarks' : string,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addStudent' : ActorMethod<[Student], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAlumni' : ActorMethod<[Alumni], bigint>,
  'createCourse' : ActorMethod<[Course], bigint>,
  'createGalleryItem' : ActorMethod<[string, ExternalBlob], bigint>,
  'createNotice' : ActorMethod<[Notice], bigint>,
  'createResult' : ActorMethod<[Result], bigint>,
  'deleteAlumni' : ActorMethod<[bigint], undefined>,
  'deleteCourse' : ActorMethod<[bigint], undefined>,
  'deleteGalleryItem' : ActorMethod<[bigint], undefined>,
  'deleteNotice' : ActorMethod<[bigint], undefined>,
  'deleteResult' : ActorMethod<[bigint], undefined>,
  'deleteStudent' : ActorMethod<[string], undefined>,
  'getAboutText' : ActorMethod<[], string>,
  'getAllAlumni' : ActorMethod<[], Array<Alumni>>,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getAllGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getAllNotices' : ActorMethod<[], Array<Notice>>,
  'getAllResults' : ActorMethod<[], Array<Result>>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getAlumni' : ActorMethod<[bigint], [] | [Alumni]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactInfo' : ActorMethod<[], ContactInfo>,
  'getCourse' : ActorMethod<[bigint], [] | [Course]>,
  'getGalleryItem' : ActorMethod<[bigint], [] | [GalleryItem]>,
  'getNotice' : ActorMethod<[bigint], [] | [Notice]>,
  'getResult' : ActorMethod<[bigint], [] | [Result]>,
  'getStudent' : ActorMethod<[string], [] | [Student]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAboutText' : ActorMethod<[string], undefined>,
  'updateAlumni' : ActorMethod<[bigint, Alumni], undefined>,
  'updateContactInfo' : ActorMethod<[ContactInfo], undefined>,
  'updateCourse' : ActorMethod<[bigint, Course], undefined>,
  'updateGalleryItem' : ActorMethod<[bigint, string], undefined>,
  'updateNotice' : ActorMethod<[bigint, Notice], undefined>,
  'updateResult' : ActorMethod<[bigint, Result], undefined>,
  'updateStudent' : ActorMethod<[Student], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];